/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetomatematica;

/**
 *
 * @author TI431
 */
public class Eq extends javax.swing.JFrame {

    
    double C;
    double C2;
    double L;
    double L2;
    
    public Eq() {
        initComponents();
        setSize(700,500);
    }

    
    public int getDenominador(int x, int y){
        int valor = 2;
        int menor = x;
        boolean achei = false;
        if (y < menor)
            menor = y;
        while( valor <= menor && !achei){
            if (x % valor == 0 && y % valor ==0)
               achei = true;
            else
              valor++;           
        }
         if (achei)
             return valor;
         return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Comprimento de um arco:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 21, 312, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Dada uma circunferência de centro O, raio r e dois pontos A e B pertencentes à circunferência, ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(51, 61, 579, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("temos que a distância entre os pontos assinalados é um arco de circunferência. O comprimento ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(51, 84, 585, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("de um arco é proporcional à medida do ângulo central.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(51, 107, 340, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetomatematica/arco.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(51, 155, 166, 149);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("C = 2.π.r");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(266, 178, 80, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Comprimento da circunferência:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(266, 155, 196, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Comprimento da circunferência linear:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(266, 287, 231, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Digite o valor do raio:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(266, 224, 116, 15);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(386, 208, 137, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("C=");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 257, 90, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 160, 79, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Limpar");
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 210, 79, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText(" ℓ = α .r .π");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(277, 335, 89, 22);

        jLabel12.setText("__________");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 334, 90, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("180°");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 360, 34, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Digite o valor do raio:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(280, 390, 130, 15);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(410, 380, 100, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText(" ℓ =");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 430, 31, 22);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton1.setText("Calcular");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(574, 320, 90, 23);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton2.setText("Limpar");
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(580, 380, 80, 20);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 350, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // calcular
        C = Double.parseDouble(jTextField1.getText());
        if(C!=0){
        C2 = 2*C*(3.1415926595897932384626433832795);
        jLabel10.setText(""+C2);  }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int x = 20;
        int y = 100;
        int d = getDenominador(x, y);
        while(d > 0){
            x = x/d;
            y = y/d;
            System.out.println(""+ x + "/" + y);
            d = getDenominador(x, y);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eq().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
