/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetomatematica;

import javax.swing.JOptionPane;

/**
 *
 * @author driu
 */
public class Lei extends javax.swing.JFrame {

    double C;
    double A;
    double B;
    double R;
    double Raiz;
    double C2;
    double X;//a
    double X2;//b
    double Y;//sena
    double Y2;//senb
    double V;
    double D;

    public Lei() {
        initComponents();
        setSize(1000, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lei do cosseno e seno:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 11, 290, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("c²=a² + b² -2.a.b.cosC");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 208, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("a = b");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 90, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText(" __     __");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 90, 120, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Digite o valor de c:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 130, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Digite o valor de a:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 210, 130, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Digite o valor de b:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 250, 120, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Digite o valor do cosseno:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 290, 170, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Resultado:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 340, 80, 17);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 410, 90, 23);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 160, 70, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 200, 70, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 240, 70, 30);

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 280, 70, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 410, 71, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("senA  senB");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 120, 120, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Digite o valor de a:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 170, 130, 17);

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(480, 160, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Digite o valor de b:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 220, 130, 17);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(480, 210, 80, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Digite o seno de A:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(330, 270, 120, 17);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(480, 260, 80, 30);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(480, 310, 80, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Digite o seno de B:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 320, 130, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Resultado:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 370, 80, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 410, 80, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(480, 410, 71, 23);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(480, 354, 80, 40);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(210, 324, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // calcular
        if (jTextField1.getText().trim().isEmpty()) {
            try {
                A = Double.parseDouble(jTextField2.getText());
                B = Double.parseDouble(jTextField3.getText());
                C2 = Double.parseDouble(jTextField4.getText());
                R = Math.pow(A, 2) + Math.pow(B, 2) - (2 * A * B * C2);
                if (R < 0) {
                    JOptionPane.showMessageDialog(null, "Não é possivel calcular raiz negativa.");
                } else {
                    Raiz = Math.sqrt(R);
                      jLabel17.setText("" + Raiz);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
            }
        } else if (jTextField2.getText().trim().isEmpty()) {
            //definindo o valor de A
            try {
                C = Double.parseDouble(jTextField1.getText());
                B = Double.parseDouble(jTextField3.getText());
                C2 = Double.parseDouble(jTextField4.getText());
                R = Math.pow(C, 2) - Math.pow(B, 2) + (2 * B * C2);
                if (R < 0) {
                    JOptionPane.showMessageDialog(null, "Não é possivel calcular raiz negativa.");
                } else {
                    Raiz = Math.sqrt(R);
                     jLabel17.setText("" + Raiz);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
            }

        } else if (jTextField3.getText().trim().isEmpty()) {
            try {
                A = Double.parseDouble(jTextField2.getText());
                C = Double.parseDouble(jTextField1.getText());
                C2 = Double.parseDouble(jTextField4.getText());
                R = Math.pow(C, 2) - Math.pow(A, 2) + (2 * A * C2);
                if (R < 0) {
                    JOptionPane.showMessageDialog(null, "Não é possivel calcular raiz negativa.");
                } else {
                    Raiz = Math.sqrt(R);
                      jLabel17.setText("" + Raiz);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
            }
        } else if (jTextField4.getText().trim().isEmpty()) {
            try {
                A = Double.parseDouble(jTextField1.getText());
                B = Double.parseDouble(jTextField2.getText());
                C = Double.parseDouble(jTextField3.getText());
                D = -2*A*B;
                if(D !=0){
                R = Math.pow(C, 2) - Math.pow(A, 2) - Math.pow(B, 2) / -(2 * A * B);
                  jLabel17.setText("" + R);}
                else
                     JOptionPane.showMessageDialog(null,"não é possível dividir por zero");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você precisa deixar um campo em branco para o cálculo.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // cossemo
        C2 = Double.parseDouble(jTextField4.getText());
        if (C2 == 0) {
            JOptionPane.showMessageDialog(null, " você deve voltar a calcular através do teorema de Pitágoras");
            jTextField4.setText("");
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // limpar
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jLabel17.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // calcular seno
        if (jTextField6.getText().trim().isEmpty()) {
            try {
                X2 = Double.parseDouble(jTextField7.getText());//seno a
                Y = Double.parseDouble(jTextField8.getText()); //b
                Y2 = Double.parseDouble(jTextField9.getText());//seno b
                if(Y2 !=0){
                V = (Y / Y2) * X2;
                 jLabel16.setText("" + V);}
                else 
                     JOptionPane.showMessageDialog(null,"não é possível dividir por zero.");
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
            }}
           else if (jTextField7.getText().trim().isEmpty()) {
                try {
                    X = Double.parseDouble(jTextField6.getText());
                    Y = Double.parseDouble(jTextField8.getText());
                    Y2 = Double.parseDouble(jTextField9.getText());
                    if(Y != 0){
                    V = (X * Y2) / Y;
                     jLabel16.setText("" + V);}
                    else 
                         JOptionPane.showMessageDialog(null,"não é possível dividir por zero");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
                }}
               else if (jTextField8.getText().trim().isEmpty()) {
                    try {
                        X = Double.parseDouble(jTextField6.getText());
                        X2 = Double.parseDouble(jTextField7.getText());
                        Y2 = Double.parseDouble(jTextField9.getText());
                        if(X2 !=0){
                        V = (X / X2) * Y2;
                        jLabel16.setText("" + V);}
                        else
                             JOptionPane.showMessageDialog(null,"não é possível dividir por zero");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
                    }
                }
               else if (jTextField9.getText().trim().isEmpty()) {
                    try {
                        X = Double.parseDouble(jTextField6.getText());
                        X2 = Double.parseDouble(jTextField7.getText());
                        Y = Double.parseDouble(jTextField8.getText());
                        if(X !=0){
                        V = (Y*X2)/X;
                        jLabel16.setText("" + V);}
                        else
                             JOptionPane.showMessageDialog(null,"não é possível dividir por zero");
                        
                    }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao calcular. " + e.getMessage());
                }} else {
            JOptionPane.showMessageDialog(null, "Você precisa deixar um campo em branco para o cálculo.");
        }
            
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6FocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // limpar 2
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jLabel16.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lei().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
